### ISSUE TITLE
search fuction

### ISSUE THREAD

**Issue by Wizart009** [lantzelot-swe/PCUGameManager#11]
can you add a good and easy and advanced search fuction to the manager ?

**Comment by lantzelot-swe** [comment]
Hi, thanks for your request.

How would you like to be able to search?

I have no plans for adding a search function right now. To find a game in the game list you can type the beginning of the title to jump in the list automatically. Adding a more advanced search function would mean that the results has to be presented somewhere, or filtered in the list in some way. I think this would be a lot of work.

**Comment by DarthVader199** [comment]
i hope you do i know its a lot of work but very useful

**Comment by Wizart009** [comment]
are you have plans for search function now ?

**Comment by lantzelot-swe** [comment]
Looking into this now, I may have something ready soon.

**Comment by Wizart009** [comment]
cool thnks :)

**Comment by lantzelot-swe** [comment]
Check out version 2.12.0 :-)
