### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Wizart009** [lantzelot-swe/PCUGameManager#16]
found a bug when importing gambase all games the first option in the menu
it would make folders and place there no more than 255 games in it but folders with 2 or 3 and on they are emty
en the main folder contains to much games hope you understand :)
![Naamloos](https://github.com/lantzelot-swe/PCUGameManager/assets/15015535/8c41db6d-d888-429f-9924-7c4604a9c77d)

**Comment by lantzelot-swe** [comment]
It's actually as designed right now, dividing up the games on different views became a bit tricky in the code. I can look into if it's possible to split the games easily.

**Comment by Wizart009** [comment]
cool Thnks :)

**Comment by lantzelot-swe** [comment]
I managed to figure out how to split the games into game views.

Game views are created so that each contain a maximum of 250 files. Games are sorted alphabetically and the game views are named after the first letter of the first and last game in the view (e.g. "A-E").
