### ISSUE TITLE
Full Keyboard to Joystick Mappings

### ISSUE THREAD

**Issue by IgoSplashman** [lantzelot-swe/PCUGameManager#17]
Hi,
I just wanted to add "Snake Byte" to my game list, but then I noticed that I won't be able to play it, because the original game does not support joystick-controls and the snake can only controlled with the , and . keys.
Of course I could just go and map these keys to the joystick, but the . key is nowhere to be found in the configurator list (only the ,-key is). A few more are also missing: **← + - @ * ! [ ] = /**

![2023-08-18_18183346_PCUAE_Manager_v 2 11 3](https://github.com/lantzelot-swe/PCUGameManager/assets/7331514/31acf815-a1b7-4aae-907a-445590101e8e) ![2023-08-18_18183335_PCUAE_Manager_v 2 11 3](https://github.com/lantzelot-swe/PCUGameManager/assets/7331514/ff21ae1f-802a-4d07-b949-4decc659db5a)  ![2023-08-18_18183324_PCUAE_Manager_v 2 11 3](https://github.com/lantzelot-swe/PCUGameManager/assets/7331514/177ca55f-1a2b-4891-8d32-6e295f9a0fc5)

1. Would it be possible to add these missing keys to the joystick configurator and make the full C64 keyboard available?
2. In the meantime, is there a list for the full C64 keyboard mappings, so I could change my game config files manually?

**Comment by lantzelot-swe** [comment]
Hi, the mappings that are possible to do is limited to the list on page 69 of TheC64 manual (https://retrogames.biz/support/thec64/manuals/), so I'm afraid it's not possible to do that mapping. The manager creates .cjm files and already lists all supported key mappings. It would require a fix from Retro games and a new firmware to support the missing keys.

**Comment by IgoSplashman** [comment]
Oh, I see.
That's too bad then, but thanks for clearing it up.
