### ISSUE TITLE
progress window

### ISSUE THREAD

**Issue by Wizart009** [lantzelot-swe/PCUGameManager#18]
Suggestion maybe progress window when you delete games ?
now it just hangs when deleting lot of games takes a while to come back

**Comment by lantzelot-swe** [comment]
Deleting multiple games was very slow, I have optimized the code so that it's much faster. I also added a wait-cursor to the mouse pointer, so no need for a progress window anymore. Fixed in 2.12.3.

**Comment by Wizart009** [comment]
cool :)
