### ISSUE TITLE
Export games issue

### ISSUE THREAD

**Issue by Wizart009** [lantzelot-swe/PCUGameManager#19]
when exporting gamebase 64 to PCUAE Usb drive it make subfolders and they are not visible in PCUAE

**Comment by lantzelot-swe** [comment]
Ok, I only export gamebase to file loader... there it's nice to get subfolders. I can fix so that "/" in a game view name is replaced with "-" when exporting to carousel, then there will be no subfolders.

**Comment by Wizart009** [comment]
cool Thnks :)

**Comment by lantzelot-swe** [comment]
Fixed in 2.13.1
