### ISSUE TITLE
Add THEGamepad from THEA500 Mini to PCUAE Manager

### ISSUE THREAD

**Issue by CommodoreOS** [lantzelot-swe/PCUGameManager#20]
THEGamepad does work with THEC64 Mini, THEC64 Maxi and THEVIC20 and you can buy it separately so buy it on its own without buying THEA500 Mini(it comes in the colour black) so might be a good idea to add it too, you added THEMouse... :) 

`THEGamepad -               Y      B    A     X       LSB RSB Menu  Home`
`THEC64 Joystick -        LFire Rfire TLfire TRfire    A   B   C    Menu`

I know its not a issue but might not see it if I add it as a idea discussion.

**Comment by lantzelot-swe** [comment]
Ok, that might be feasible, so, are you thinking about having a different checkbox in the UI to select the gamepad, and then get an image of the gamepad mapped towards the buttons. Something like this (a mockup, I know... :-)) :
![Gamepad mockup](https://github.com/lantzelot-swe/PCUGameManager/assets/75668734/1f0a7615-f367-4f1c-a203-9943908192e5)

**Comment by lantzelot-swe** [comment]
I added TheGamepad in version 2.14.0, in the "edit controller" dialog.
