### ISSUE TITLE
right click

### ISSUE THREAD

**Issue by Wizart009** [lantzelot-swe/PCUGameManager#21]
right click does not work in gamelist is this on purpose ?

**Comment by lantzelot-swe** [comment]
Hi, sorry, but what do you mean? Where do you right-click and what do you expect to happen?

**Comment by Wizart009** [comment]
i mean in on left so you can copy or something or add to favorites or add to gamelist like that :)

**Comment by lantzelot-swe** [comment]
ok, I see. The "Edit" menu is pretty much the same thing, there you can perform actions for the game you have selected in the list.
In version 2.16.2 i moved the "clear favorites" options to the "Tools" menu instead, since the Edit menu is supposed to perform actions on the selected games.

**Comment by Wizart009** [comment]
i think its handy like inserting gamlist or that kind of things but i understand  :)
