### ISSUE TITLE
Getting a Requires a Java Runtime Environment 14 Error Message

### ISSUE THREAD

**Issue by technofox01** [lantzelot-swe/PCUGameManager#5]
Hi!

I just recently downloaded v1.2.2 of your program and I keep on getting this error message - even though I have installed the latest version of the Java Runtime environment, I am still getting this error message. I am running Windows 10. I appreciate any help on this.

**Comment by lantzelot-swe** [comment]
Hi, I guess you just downloaded the 1.2.2 exe file and tried to run it? You need a "full version" that includes a JRE, you can get it from this post: [pcu-game-manager-released](https://thec64community.online/thread/603/pcu-game-manager-released?page=1), here is the direct download folder: [spannernicks onedrive](https://onedrive.live.com/?authkey=%21ABk%2DxxKnx%2DBeuIo&id=DE6843E1C82A96C8%2148803&cid=DE6843E1C82A96C8)

When you have that you can just donwload the latest exe from here and replace it to run the latest version.

**Comment by technofox01** [comment]
Hi,

Thank you for helping me out. I got it working with the links that you have provided. I sincerely appreciate it :-)

**Comment by lantzelot-swe** [comment]
No problem, great that it works now.
